[project]
name = "solis_energy_manager"
requires-python = ">=3.13,<3.14"
version = "0.1.0"
dependencies = [
    "dagster==1.13.21",
    "pingram-python>=1.0.31",
    "pydantic-settings>=2.15.0",
    "dagster-docker",
    "dagster-webserver",
    "dagster-postgres",
    "dagster-graphql"
]

[dependency-groups]
dev = [
    "dagster-dg-cli",
    "dagster-webserver",
    "pre-commit>=4.6.2",
    "pytest"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
force-include = { "pyproject.toml" = "pyproject.toml" }

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "solis_energy_manager"
# code_location_name = "solis_energy_manager.definitions"
# registry_modules = [
#     "solis_energy_manager.components.*",
# ]
